/** @format */

const countriesList = [
  { AF: ["AF", "AFG", 93, "Afghanistan"] },
  { AL: ["AL", "ALB", 355, "Albania"] },
  { DZ: ["DZ", "DZA", 213, "Algeria"] },
  // { AS: ["AS", "ASM", "1-684", "American Samoa"] },
  { AD: ["AD", "AND", 376, "Andorra"] },
  { AO: ["AO", "AGO", 244, "Angola"] },
  // { AI: ["AI", "AIA", "1-264", "Anguilla"] },
  { AQ: ["AQ", "ATA", 672, "Antarctica"] },
  // { AG: ["AG", "ATG", "1-268", "Antigua and Barbuda"] },
  { AR: ["AR", "ARG", 54, "Argentina"] },
  { AM: ["AM", "ARM", 374, "Armenia"] },
  { AW: ["AW", "ABW", 297, "Aruba"] },
  { AU: ["AU", "AUS", 61, "Australia"] },
  { AT: ["AT", "AUT", 43, "Austria"] },
  { AZ: ["AZ", "AZE", 994, "Azerbaijan"] },
  // { BS: ["BS", "BHS", "1-242", "Bahamas"] },
  { BH: ["BH", "BHR", 973, "Bahrain"] },
  { BD: ["BD", "BGD", 880, "Bangladesh"] },
  // { BB: ["BB", "BRB", "1-246", "Barbados"] },
  { BY: ["BY", "BLR", 375, "Belarus"] },
  { BE: ["BE", "BEL", 32, "Belgium"] },
  { BZ: ["BZ", "BLZ", 501, "Belize"] },
  { BJ: ["BJ", "BEN", 229, "Benin"] },
  // { BM: ["BM", "BMU", "1-441", "Bermuda"] },
  { BT: ["BT", "BTN", 975, "Bhutan"] },
  { BO: ["BO", "BOL", 591, "Bolivia"] },
  { BA: ["BA", "BIH", 387, "Bosnia and Herzegovina"] },
  { BW: ["BW", "BWA", 267, "Botswana"] },
  { BR: ["BR", "BRA", 55, "Brazil"] },
  { IO: ["IO", "IOT", 246, "British Indian Ocean Territory"] },
  // { VG: ["VG", "VGB", "1-284", "British Virgin Islands"] },
  { BN: ["BN", "BRN", 673, "Brunei"] },
  { BG: ["BG", "BGR", 359, "Bulgaria"] },
  { BF: ["BF", "BFA", 226, "Burkina Faso"] },
  { BI: ["BI", "BDI", 257, "Burundi"] },
  { KH: ["KH", "KHM", 855, "Cambodia"] },
  { CM: ["CM", "CMR", 237, "Cameroon"] },
  { CA: ["CA", "CAN", 1, "Canada"] },
  { CV: ["CV", "CPV", 238, "Cape Verde"] },
  // { KY: ["KY", "CYM", "1-345", "Cayman Islands"] },
  { CF: ["CF", "CAF", 236, "Central African Republic"] },
  { TD: ["TD", "TCD", 235, "Chad"] },
  { CL: ["CL", "CHL", 56, "Chile"] },
  { CN: ["CN", "CHN", 86, "China"] },
  { CX: ["CX", "CXR", 61, "Christmas Island"] },
  { CC: ["CC", "CCK", 61, "Cocos Islands"] },
  { CO: ["CO", "COL", 57, "Colombia"] },
  { KM: ["KM", "COM", 269, "Comoros"] },
  { CK: ["CK", "COK", 682, "Cook Islands"] },
  { CR: ["CR", "CRI", 506, "Costa Rica"] },
  { HR: ["HR", "HRV", 385, "Croatia"] },
  { CU: ["CU", "CUB", 53, "Cuba"] },
  { CW: ["CW", "CUW", 599, "Curacao"] },
  { CY: ["CY", "CYP", 357, "Cyprus"] },
  { CZ: ["CZ", "CZE", 420, "Czech Republic"] },
  { CD: ["CD", "COD", 243, "Democratic Republic of the Congo"] },
  { DK: ["DK", "DNK", 45, "Denmark"] },
  { DJ: ["DJ", "DJI", 253, "Djibouti"] },
  // { DM: ["DM", "DMA", "1-767", "Dominica"] },
  // { DO: ["DO", "DOM", "1-809, 1-829, 1-849", "Dominican Republic"] },
  { TL: ["TL", "TLS", 670, "East Timor"] },
  { EC: ["EC", "ECU", 593, "Ecuador"] },
  { EG: ["EG", "EGY", 20, "Egypt"] },
  { SV: ["SV", "SLV", 503, "El Salvador"] },
  { GQ: ["GQ", "GNQ", 240, "Equatorial Guinea"] },
  { ER: ["ER", "ERI", 291, "Eritrea"] },
  { EE: ["EE", "EST", 372, "Estonia"] },
  { ET: ["ET", "ETH", 251, "Ethiopia"] },
  { FK: ["FK", "FLK", 500, "Falkland Islands"] },
  { FO: ["FO", "FRO", 298, "Faroe Islands"] },
  { FJ: ["FJ", "FJI", 679, "Fiji"] },
  { FI: ["FI", "FIN", 358, "Finland"] },
  { FR: ["FR", "FRA", 33, "France"] },
  { PF: ["PF", "PYF", 689, "French Polynesia"] },
  { GA: ["GA", "GAB", 241, "Gabon"] },
  { GM: ["GM", "GMB", 220, "Gambia"] },
  { GE: ["GE", "GEO", 995, "Georgia"] },
  { DE: ["DE", "DEU", 49, "Germany"] },
  { GH: ["GH", "GHA", 233, "Ghana"] },
  { GI: ["GI", "GIB", 350, "Gibraltar"] },
  { GR: ["GR", "GRC", 30, "Greece"] },
  { GL: ["GL", "GRL", 299, "Greenland"] },
  // { GD: ["GD", "GRD", "1-473", "Grenada"] },
  // { GU: ["GU", "GUM", "1-671", "Guam"] },
  { GT: ["GT", "GTM", 502, "Guatemala"] },
  // { GG: ["GG", "GGY", "44-1481", "Guernsey"] },
  { GN: ["GN", "GIN", 224, "Guinea"] },
  { GW: ["GW", "GNB", 245, "Guinea-Bissau"] },
  { GY: ["GY", "GUY", 592, "Guyana"] },
  { HT: ["HT", "HTI", 509, "Haiti"] },
  { HN: ["HN", "HND", 504, "Honduras"] },
  { HK: ["HK", "HKG", 852, "Hong Kong"] },
  { HU: ["HU", "HUN", 36, "Hungary"] },
  { IS: ["IS", "ISL", 354, "Iceland"] },
  { IN: ["IN", "IND", 91, "India"] },
  { ID: ["ID", "IDN", 62, "Indonesia"] },
  { IR: ["IR", "IRN", 98, "Iran"] },
  { IQ: ["IQ", "IRQ", 964, "Iraq"] },
  { IE: ["IE", "IRL", 353, "Ireland"] },
  // { IM: ["IM", "IMN", "44-1624", "Isle of Man"] },
  { IL: ["IL", "ISR", 972, "Israel"] },
  { IT: ["IT", "ITA", 39, "Italy"] },
  { CI: ["CI", "CIV", 225, "Ivory Coast"] },
  // { JM: ["JM", "JAM", "1-876", "Jamaica"] },
  { JP: ["JP", "JPN", 81, "Japan"] },
  // { JE: ["JE", "JEY", "44-1534", "Jersey"] },
  { JO: ["JO", "JOR", 962, "Jordan"] },
  { KZ: ["KZ", "KAZ", 7, "Kazakhstan"] },
  { KE: ["KE", "KEN", 254, "Kenya"] },
  { KI: ["KI", "KIR", 686, "Kiribati"] },
  { XK: ["XK", "XKX", 383, "Kosovo"] },
  { KW: ["KW", "KWT", 965, "Kuwait"] },
  { KG: ["KG", "KGZ", 996, "Kyrgyzstan"] },
  { LA: ["LA", "LAO", 856, "Laos"] },
  { LV: ["LV", "LVA", 371, "Latvia"] },
  { LB: ["LB", "LBN", 961, "Lebanon"] },
  { LS: ["LS", "LSO", 266, "Lesotho"] },
  { LR: ["LR", "LBR", 231, "Liberia"] },
  { LY: ["LY", "LBY", 218, "Libya"] },
  { LI: ["LI", "LIE", 423, "Liechtenstein"] },
  { LT: ["LT", "LTU", 370, "Lithuania"] },
  { LU: ["LU", "LUX", 352, "Luxembourg"] },
  { MO: ["MO", "MAC", 853, "Macau"] },
  { MK: ["MK", "MKD", 389, "Macedonia"] },
  { MG: ["MG", "MDG", 261, "Madagascar"] },
  { MW: ["MW", "MWI", 265, "Malawi"] },
  { MY: ["MY", "MYS", 60, "Malaysia"] },
  { MV: ["MV", "MDV", 960, "Maldives"] },
  { ML: ["ML", "MLI", 223, "Mali"] },
  { MT: ["MT", "MLT", 356, "Malta"] },
  { MH: ["MH", "MHL", 692, "Marshall Islands"] },
  { MR: ["MR", "MRT", 222, "Mauritania"] },
  { MU: ["MU", "MUS", 230, "Mauritius"] },
  { YT: ["YT", "MYT", 262, "Mayotte"] },
  { MX: ["MX", "MEX", 52, "Mexico"] },
  { FM: ["FM", "FSM", 691, "Micronesia"] },
  { MD: ["MD", "MDA", 373, "Moldova"] },
  { MC: ["MC", "MCO", 377, "Monaco"] },
  { MN: ["MN", "MNG", 976, "Mongolia"] },
  { ME: ["ME", "MNE", 382, "Montenegro"] },
  // { MS: ["MS", "MSR", "1-664", "Montserrat"] },
  { MA: ["MA", "MAR", 212, "Morocco"] },
  { MZ: ["MZ", "MOZ", 258, "Mozambique"] },
  { MM: ["MM", "MMR", 95, "Myanmar"] },
  { NA: ["NA", "NAM", 264, "Namibia"] },
  { NR: ["NR", "NRU", 674, "Nauru"] },
  { NP: ["NP", "NPL", 977, "Nepal"] },
  { NL: ["NL", "NLD", 31, "Netherlands"] },
  // { AN: ["AN", "ANT", 599, "Netherlands Antilles"] },
  { NC: ["NC", "NCL", 687, "New Caledonia"] },
  { NZ: ["NZ", "NZL", 64, "New Zealand"] },
  { NI: ["NI", "NIC", 505, "Nicaragua"] },
  { NE: ["NE", "NER", 227, "Niger"] },
  { NG: ["NG", "NGA", 234, "Nigeria"] },
  { NU: ["NU", "NIU", 683, "Niue"] },
  { KP: ["KP", "PRK", 850, "North Korea"] },
  // { MP: ["MP", "MNP", "1-670", "Northern Mariana Islands"] },
  { NO: ["NO", "NOR", 47, "Norway"] },
  { OM: ["OM", "OMN", 968, "Oman"] },
  { PK: ["PK", "PAK", 92, "Pakistan"] },
  { PW: ["PW", "PLW", 680, "Palau"] },
  { PS: ["PS", "PSE", 970, "Palestine"] },
  { PA: ["PA", "PAN", 507, "Panama"] },
  { PG: ["PG", "PNG", 675, "Papua New Guinea"] },
  { PY: ["PY", "PRY", 595, "Paraguay"] },
  { PE: ["PE", "PER", 51, "Peru"] },
  { PH: ["PH", "PHL", 63, "Philippines"] },
  { PN: ["PN", "PCN", 64, "Pitcairn"] },
  { PL: ["PL", "POL", 48, "Poland"] },
  { PT: ["PT", "PRT", 351, "Portugal"] },
  // { PR: ["PR", "PRI", "1-787, 1-939", "Puerto Rico"] },
  { QA: ["QA", "QAT", 974, "Qatar"] },
  { CG: ["CG", "COG", 242, "Republic of the Congo"] },
  { RE: ["RE", "REU", 262, "Reunion"] },
  { RO: ["RO", "ROU", 40, "Romania"] },
  { RU: ["RU", "RUS", 7, "Russia"] },
  { RW: ["RW", "RWA", 250, "Rwanda"] },
  { BL: ["BL", "BLM", 590, "Saint Barthelemy"] },
  { SH: ["SH", "SHN", 290, "Saint Helena"] },
  // { KN: ["KN", "KNA", "1-869", "Saint Kitts and Nevis"] },
  // { LC: ["LC", "LCA", "1-758", "Saint Lucia"] },
  { MF: ["MF", "MAF", 590, "Saint Martin"] },
  { PM: ["PM", "SPM", 508, "Saint Pierre and Miquelon"] },
  // { VC: ["VC", "VCT", "1-784", "Saint Vincent and the Grenadines"] },
  { WS: ["WS", "WSM", 685, "Samoa"] },
  { SM: ["SM", "SMR", 378, "San Marino"] },
  { ST: ["ST", "STP", 239, "Sao Tome and Principe"] },
  { SA: ["SA", "SAU", 966, "Saudi Arabia"] },
  { SN: ["SN", "SEN", 221, "Senegal"] },
  { RS: ["RS", "SRB", 381, "Serbia"] },
  { SC: ["SC", "SYC", 248, "Seychelles"] },
  { SL: ["SL", "SLE", 232, "Sierra Leone"] },
  { SG: ["SG", "SGP", 65, "Singapore"] },
  // { SX: ["SX", "SXM", "1-721", "Sint Maarten"] },
  { SK: ["SK", "SVK", 421, "Slovakia"] },
  { SI: ["SI", "SVN", 386, "Slovenia"] },
  { SB: ["SB", "SLB", 677, "Solomon Islands"] },
  { SO: ["SO", "SOM", 252, "Somalia"] },
  { ZA: ["ZA", "ZAF", 27, "South Africa"] },
  { KR: ["KR", "KOR", 82, "South Korea"] },
  { SS: ["SS", "SSD", 211, "South Sudan"] },
  { ES: ["ES", "ESP", 34, "Spain"] },
  { LK: ["LK", "LKA", 94, "Sri Lanka"] },
  { SD: ["SD", "SDN", 249, "Sudan"] },
  { SR: ["SR", "SUR", 597, "Suriname"] },
  { SJ: ["SJ", "SJM", 47, "Svalbard and Jan Mayen"] },
  { SZ: ["SZ", "SWZ", 268, "Swaziland"] },
  { SE: ["SE", "SWE", 46, "Sweden"] },
  { CH: ["CH", "CHE", 41, "Switzerland"] },
  { SY: ["SY", "SYR", 963, "Syria"] },
  { TW: ["TW", "TWN", 886, "Taiwan"] },
  { TJ: ["TJ", "TJK", 992, "Tajikistan"] },
  { TZ: ["TZ", "TZA", 255, "Tanzania"] },
  { TH: ["TH", "THA", 66, "Thailand"] },
  { TG: ["TG", "TGO", 228, "Togo"] },
  { TK: ["TK", "TKL", 690, "Tokelau"] },
  { TO: ["TO", "TON", 676, "Tonga"] },
  // { TT: ["TT", "TTO", "1-868", "Trinidad and Tobago"] },
  { TN: ["TN", "TUN", 216, "Tunisia"] },
  { TR: ["TR", "TUR", 90, "Turkey"] },
  { TM: ["TM", "TKM", 993, "Turkmenistan"] },
  // { TC: ["TC", "TCA", "1-649", "Turks and Caicos Islands"] },
  { TV: ["TV", "TUV", 688, "Tuvalu"] },
  // { VI: ["VI", "VIR", "1-340", "U.S. Virgin Islands"] },
  { UG: ["UG", "UGA", 256, "Uganda"] },
  { UA: ["UA", "UKR", 380, "Ukraine"] },
  { AE: ["AE", "ARE", 971, "United Arab Emirates"] },
  { GB: ["GB", "GBR", 44, "United Kingdom"] },
  { US: ["US", "USA", 1, "United States"] },
  { UY: ["UY", "URY", 598, "Uruguay"] },
  { UZ: ["UZ", "UZB", 998, "Uzbekistan"] },
  { VU: ["VU", "VUT", 678, "Vanuatu"] },
  { VA: ["VA", "VAT", 379, "Vatican"] },
  { VE: ["VE", "VEN", 58, "Venezuela"] },
  { VN: ["VN", "VNM", 84, "Vietnam"] },
  { WF: ["WF", "WLF", 681, "Wallis and Futuna"] },
  { EH: ["EH", "ESH", 212, "Western Sahara"] },
  { YE: ["YE", "YEM", 967, "Yemen"] },
  { ZM: ["ZM", "ZMB", 260, "Zambia"] },
  { ZW: ["ZW", "ZWE", 263, "Zimbabwe"] },
]; //.sort((val1, val2) => Object.values(val1)[0][2] - Object.values(val2)[0][2]);

export default countriesList;
