/** @format */
import assert from "assert";

const {
  // PORT,
  NODE_ENV,
  // CYPRESS_HOST,
  REACT_APP_SERVER_API,
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
  REACT_APP_FIREBASE_MEASUREMENT_ID,
} = process.env;

// NOTE: This is for test in production
console.log(
  // PORT,
  NODE_ENV,
  // CYPRESS_HOST,
  REACT_APP_SERVER_API,
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
  REACT_APP_FIREBASE_MEASUREMENT_ID
);

// assert(PORT, "PORT value is required");
assert(NODE_ENV, "NODE_ENV value is required");
assert(REACT_APP_SERVER_API, "REACT_APP_SERVER_API value is required");
assert(
  REACT_APP_FIREBASE_API_KEY,
  "REACT_APP_FIREBASE_API_KEY value is required"
);
assert(
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  "REACT_APP_FIREBASE_AUTH_DOMAIN value is required"
);
assert(
  REACT_APP_FIREBASE_PROJECT_ID,
  "REACT_APP_FIREBASE_PROJECT_ID value is required"
);
assert(
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  "REACT_APP_FIREBASE_STORAGE_BUCKET value is required"
);
assert(
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  "REACT_APP_FIREBASE_MESSAGING_SENDER_ID value is required"
);
assert(
  REACT_APP_FIREBASE_APP_ID,
  "REACT_APP_FIREBASE_APP_ID value is required"
);
assert(
  REACT_APP_FIREBASE_MEASUREMENT_ID,
  "REACT_APP_FIREBASE_MEASUREMENT_ID value is required"
);
