/** @format */

export const ACCOUNT_INIT = "ACCOUNT_INIT";

export const LOG_IN_START = "LOG_IN_START";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";

export const LOG_OUT_START = "LOG_OUT_START";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_ERROR = "LOG_OUT_ERROR";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const ISSUES_GET_START = "ISSUES_GET_START";
export const ISSUES_GET_SUCCESS = "ISSUES_GET_SUCCESS";
export const ISSUES_GET_ERROR = "ISSUES_GET_ERROR";

export const ISSUE_GET_START = "ISSUE_GET_START";
export const ISSUE_GET_SUCCESS = "ISSUE_GET_SUCCESS";
export const ISSUE_GET_ERROR = "ISSUE_GET_ERROR";

export const ISSUE_UPDATE_START = "ISSUE_UPDATE_START";
export const ISSUE_UPDATE_SUCCESS = "ISSUE_UPDATE_SUCCESS";
export const ISSUE_UPDATE_ERROR = "ISSUE_UPDATE_ERROR";

export const ISSUE_CREATE_RESET = "ISSUE_CREATE_RESET";
export const ISSUE_CREATE_START = "ISSUE_CREATE_START";
export const ISSUE_CREATE_SUCCESS = "ISSUE_CREATE_SUCCESS";
export const ISSUE_CREATE_ERROR = "ISSUE_CREATE_ERROR";

export const COMMENTS_GET_START = "COMMENTS_GET_START";
export const COMMENTS_GET_SUCCESS = "COMMENTS_GET_SUCCESS";
export const COMMENTS_GET_ERROR = "COMMENTS_GET_ERROR";

export const COMMENT_CREATE_RESET = "COMMENT_CREATE_RESET";
export const COMMENT_CREATE_START = "COMMENT_CREATE_START";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_ERROR = "COMMENT_CREATE_ERROR";

export const NOTIFICATIONS_GET_START = "NOTIFICATIONS_GET_START";
export const NOTIFICATIONS_GET_SUCCESS = "NOTIFICATIONS_GET_SUCCESS";
export const NOTIFICATIONS_GET_ERROR = "NOTIFICATIONS_GET_ERROR";
